name: CI

on:
  push:
    branches:
      - main

jobs:

  frontend:

    uses: ./.github/workflows/reusable-build.yaml

    with:
      service: frontend
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
      image_name: stock-alert-frontend